services:
  ia-agent-service:
    image: ia-agent-service
    container_name: ia-agent-service
    environment:
      - PORT=8102
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://marcelomoreirasouza:9lN1u5TMC2yKsU32@botsoluti.q4mfu.mongodb.net/botsoluti-dev?retryWrites=true&w=majority
      - REDIS_URI=redis://localhost:6379
      - REDIS_DB=1
      - AUTH_SERVICE_HOST=http://localhost:8091/private
      - LOGGER_SERVICE_HOST=http://localhost:8070
      - BOT_SERVICE_HOST=http://localhost:8095/private
      - CONTACT_SERVICE_HOST=http://localhost:8096/private
    ports:
      - "8102:8102"
    network_mode: "host"

# docker build . -t ia-agent-service
# docker tag ia-agent-service mmoreirasouza/ia-agent-service
# docker push mmoreirasouza/ia-agent-service
# no servidor para atualizar a imagem: docker pull mmoreirasouza/ia-agent-service
