name: Trigger auto deployment for ia-agent-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ia-agent-service-AutoDeployTrigger-59452f5a-b2e9-46a9-b5c9-e2fb3b40317d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IAAGENTSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IAAGENTSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IAAGENTSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: registry.hub.docker.com
          registryUsername: ${{ secrets.IAAGENTSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IAAGENTSERVICE_REGISTRY_PASSWORD }}
          containerAppName: ia-agent-service
          resourceGroup: rg-container-app-botsoluti
          imageToBuild: registry.hub.docker.com/mmoreirasouza/ia-agent-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


